baseurl = "//fchauvel.github.io"
languageCode = "en-us"
title = "Franck Chauvel"
# Enable comments by entering your Disqus shortname
disqusShortname = "fchauvel-net"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "Franck Chauvel"
    bio = "Programmer doing Research"
    location = "Ålesund, Norway"
    site_description = "Franck's Personal Page"
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."
    avatar = "images/avatar.jpg"
    logo = "images/logo.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Biography"
    link   = "biography/"

[[params.menu]]
    before = false
    label  = "Research"
    link   = "research/"

[[params.menu]]
    before = false
    label  = "Publications"
    link   = "publication-list/"

[[params.menu]]
    before = false
    label  = "Software"
    link   = "software/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/fchauvel"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "fchauvel"
    gitlab          = "fchauvel"
    bitbucket       = "fchauvel"
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "fchauvel"
    slideshare      = ""
    stackoverflow   = "7404838"
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "fchauvel1"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4